### ISSUE TITLE
Update framework-arduinoteensy

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-teensy#10]
Teensyduino has been updated to 1.34:

https://www.pjrc.com/teensy/td_download.html

The most recent tag is see from @PaulStoffregen is 1.31:

https://github.com/PaulStoffregen/cores/tree/1.31

Thanks!

**Comment by PaulStoffregen** [comment]
yup, looks like I'm not diligent about tagging releases....

**Comment by blackketter** [comment]
@PaulStoffregen Congrats on 1.35.  Now would be a great time to tag that release.  👍

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/cores/releases/tag/1.35

**Comment by ivankravets** [comment]
@PaulStoffregen How about for soft reset for CLI tool?

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-teensy/releases/tag/v1.6.0

**Comment by PaulStoffregen** [comment]
> How about for soft reset for CLI tool?

Like this?
https://github.com/PaulStoffregen/teensy_loader_cli/blob/master/teensy_loader_cli.c#L43

Hopefully that can help, because the reality is I'm not planning to do anything more with the command line loader in the foreseeable future.  So many other things are higher priority, like migrating Teensy to a newer version of gcc, and support for the 2nd USB port on Teensy 3.6, and much needed improvements in my long-neglected documentation.

**Comment by ivankravets** [comment]
@PaulStoffregen I mean this https://github.com/platformio/platform-teensy/issues/9#issuecomment-267958924
