### ISSUE TITLE
Teensy 1.59 has been released

### ISSUE THREAD

**Issue by skunktrading** [platformio/platform-teensy#112]
https://forum.pjrc.com/index.php?threads/teensyduino-1-59-released.74436/

**Comment by PaulStoffregen** [comment]
Please be aware Teensy is now compiling as C++17.  See #109.

**Comment by skunktrading** [comment]
Thanks for updateing so quickly :)
I was able to switch to 1.59 by putting
`platform = https://github.com/platformio/platform-teensy.git`
into my platformio.ini
In order to load the matching tools package I had to add
`platform_packages =
    tool-teensy @ 1.159.0
`
into my platformio.ini

Is this expected? I seem to remember that previous updates handled switching to the matching tools etc. without needing the override.

**Comment by PaulStoffregen** [comment]
Is PlatformIO using the libraries we publish for Teensy to use with Arduino IDE?

For the 1.59 release, they are all in this tarball.

https://www.pjrc.com/teensy/td_159/teensy-package-1.59.0.tar.zst

Asking because we recently had a lengthy forum thread where someone had all sorts of problems with mismatched SD and SdFat libraries... and eventually admitted they were using PlatformIO rather than Arduino IDE.

**Comment by PaulStoffregen** [comment]
Especially with SD cards, the core library, SD (unique for Teensy) and SdFat (fork for Teensy) we publish for Teensy really need to be used together.

When users install some other copy of SD or SdFat, things go badly.  :(

**Comment by skunktrading** [comment]
Hi Paul
As far as I can tell the correct libraries are definitely being used

**Comment by PaulStoffregen** [comment]
Thanks.  That's quite a relief to hear.
